apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: bidrag
  name: {{ name }}
  namespace: bidrag
spec:
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  webproxy: true
  accessPolicy:
      outbound:
        external:
          - host: {{ access.outbound.bidrag-sak }}
  image: {{ image }}
  replicas:
    min: 1
    max: 1
  liveness:
    path: /bidrag-cucumber-onprem/actuator/health
    initialDelay: 35
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-cucumber-onprem/actuator/health
    initialDelay: 30
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-cucumber-onprem/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  envFrom:
    - secret: test-auth-z992903
    - secret: sts-auth
  env:
    - name: SAK_SCOPE
      value: {{ scope.sak }}
    - name: BD_ARKIV_SCOPE
      value: {{scope.bd_arkiv}}
    - name: BD_JOURNALPOST_SCOPE
      value: {{scope.bd_journalpost}}
    - name: ORGANISASJON_SCOPE
      value: {{scope.organisasjon}}
    - name: DOKUMENT_SCOPE
      value: {{scope.dokument}}
    - name: PERSON_SCOPE
      value: {{scope.person}}
    - name: OPPGAVE_SCOPE
      value: {{scope.oppgave}}
    - name: BD_ARKIVERING_SCOPE
      value: {{scope.bd_arkivering}}
    - name: STS_URL
      value: https://security-token-service.dev.adeo.no
    - name: STS_USER
      value: srvbdarkiv
