management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  servlet:
    context-path: /bidrag-cucumber-onprem

springdoc:
  packages-to-scan: no.nav.bidrag.cucumber.controller

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          accepted-audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}
      client:
        registration:
          bidrag-sak:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://${SAK_SCOPE}/.default
        provider:
          aad:
            token-uri: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            jwk-set-uri: ${AZURE_OPENID_CONFIG_JWKS_URI}
