management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  servlet:
    context-path: /bidrag-cucumber-onprem
springdoc:
  packages-to-scan: no.nav.bidrag.cucumber.controller

http.proxy.parametername: prevent.isso.proxy.fss(hack)

spring:
  main.banner-mode: "off"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          accepted-audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}
      client:
        registration:
          bidrag-sak:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://${SAK_SCOPE}/.default
          oppgave-api:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://${OPPGAVE_SCOPE}/.default
          bidrag-dokument-arkiv:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://${BD_ARKIV_SCOPE}/.default
          bidrag-dokument-journalpost:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://${BD_JOURNALPOST_SCOPE}/.default
          bidrag-organisasjon:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://${ORGANISASJON_SCOPE}/.default
          bidrag-person:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://${PERSON_SCOPE}/.default
          bidrag-dokument:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://${DOKUMENT_SCOPE}/.default
          bidrag-dokument-arkivering:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://${BD_ARKIVERING_SCOPE}/.default
        provider:
          aad:
            token-uri: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            jwk-set-uri: ${AZURE_OPENID_CONFIG_JWKS_URI}
