name: build and deploy
on:
  push:
    branches:
      - '**'
      - '!feature/cron-fix'

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  INGRESS_CUCUMBER: https://bidrag-cucumber-onprem.dev.adeo.no

jobs:

  restart-testdata:
    name: restart kubernetes pods bidrag-testdata
    runs-on: self-hosted

    steps:
      - name: restart bidrag-testdata
        if: github.ref == 'refs/heads/main'
        run: "curl -X 'POST' 'https://bidrag-testdata.dev.adeo.no/bidrag-testdata/restart' -H 'accept: */*' -d ''"
      - name: restart bidrag-testdata-feature
        if: github.ref != 'refs/heads/main'
        run: "curl -X 'POST' 'https://bidrag-testdata-feature.dev.adeo.no/bidrag-testdata/restart' -H 'accept: */*' -d ''"

  build:
    name: Build with maven and docker
    runs-on: ubuntu-latest

    steps:
      - uses: navikt/bidrag-docker/exists@v1
        id: dockerimage
        with:
          image_name: bidrag-cucumber-onprem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo NOT_FOUND=${{ steps.dockerimage.outputs.not_found }} >> $GITHUB_ENV
      - uses: actions/checkout@v2
        if: env.NOT_FOUND == 'true'
      - uses: actions/setup-java@v1
        if: env.NOT_FOUND == 'true'
        with:
          java-version: '17'
      - uses: actions/cache@v1
        if: env.NOT_FOUND == 'true'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-maven/setup@v7
        if: env.NOT_FOUND == 'true'
        with:
          repositories: maven-central=https://repo.maven.apache.org/maven2,github-packages=https://maven.pkg.github.com/navikt/maven-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-maven/verify-dependencies@v7
        if: env.NOT_FOUND == 'true'
      - run: mvn install -B -e
        if: env.NOT_FOUND == 'true'
      - name: Build and publish Docker image
        if: env.NOT_FOUND == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker image build --tag ${IMAGE} .
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker image push ${IMAGE}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy bidrag-cucumber-onprem
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy
      - name: Deploy bidrag-cucumber-onprem testapplication for main branches to dev-fss
        if: github.ref == 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/.nais/nais.yaml
          VARS: deploy/.nais/main.yaml
      - name: Deploy bidrag-cucumber-onprem testapplication for feature branches to dev-fss
        if: github.ref != 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/.nais/nais.yaml
          VARS: deploy/.nais/feature.yaml

  run-tests-for-cucumber-onprem:
    runs-on: self-hosted
    name: bidrag-cucumber-onprem
    needs: deploy

    steps:
      - run: echo "INGRESS_CUCUMBER=https://bidrag-cucumber-onprem-feature.dev.adeo.no" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      - run: |
          curl -X 'POST' ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "ingressesForApps":["${{ env.INGRESS_CUCUMBER }}@tag:bidrag-cucumber-onprem"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-bidrag-beregn:
    runs-on: self-hosted
    name: bidrag-beregn-*
    needs: deploy

    env:
      INGRESS_BARNEBIDRAG: https://bidrag-beregn-barnebidrag-rest.dev.adeo.no
      INGRESS_FORSKUDD: https://bidrag-beregn-forskudd-rest.dev.adeo.no
      INGRESS_SAERTILSKUDD: https://bidrag-beregn-saertilskudd-rest.dev.adeo.no

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_BARNEBIDRAG=https://bidrag-beregn-barnebidrag-rest-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-onprem-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_FORSKUDD=https://bidrag-beregn-forskudd-rest-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_SAERTILSKUDD=https://bidrag-beregn-saertilskudd-rest-feature.dev.adeo.no" >> $GITHUB_ENV
      - name: bidrag-beregn-barnebidrag-rest
        run: |
          curl -X 'POST' ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "ingressesForApps":["${{ env.INGRESS_BARNEBIDRAG }}@tag:bidrag-beregn-barnebidrag-rest"]
          }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: bidrag-beregn-forskudd-rest
        run: |
          curl -X 'POST' ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "ingressesForApps":["${{ env.INGRESS_FORSKUDD }}@tag:bidrag-beregn-forskudd-rest"]
          }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: bidrag-beregn-saertilskudd-rest
        run: |
          curl -X 'POST' ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "ingressesForApps":["${{ env.INGRESS_SAERTILSKUDD }}@tag:bidrag-beregn-saertilskudd-rest"]
          }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-dokument:
    runs-on: self-hosted
    name: bidrag-dokument
    needs: deploy

    env:
      INGRESS_ARKIV: https://bidrag-dokument-arkiv.dev.intern.nav.no
      INGRESS_DOKARKIV: https://dokarkiv-q2.dev.adeo.no
      INGRESS_DOKUMENT: https://bidrag-dokument.dev.intern.nav.no
      INGRESS_DOKUMENT_JOURNALPOST: https://bidrag-dokument-journalpost.dev.adeo.no
      INGRESS_TESTDATA: https://bidrag-testdata.dev.adeo.no

    steps:
      - run: |
          echo "INGRESS_ARKIV=https://bidrag-dokument-arkiv-feature.dev.intern.nav.no" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-onprem-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_DOKARKIV=https://dokarkiv-q1.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_DOKUMENT=https://bidrag-dokument-feature.dev.intern.nav.no" >> $GITHUB_ENV
          echo "INGRESS_DOKUMENT_JOURNALPOST=https://bidrag-dokument-journalpost-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_TESTDATA=https://bidrag-testdata-feature.dev.adeo.no" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      - name: "@bda-samt-bdj"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@bda-samt-bdj"], "navUsername": "c151787", "testUsername": "z992903",
              "noContextPathForApps":["dokarkiv-api"],"ingressesForApps":[
                "${{ env.INGRESS_ARKIV }}@bidrag-dokument-arkiv",
                "${{ env.INGRESS_DOKARKIV }}@dokarkiv-api",
                "${{ env.INGRESS_DOKUMENT }}@bidrag-dokument",
                "${{ env.INGRESS_DOKUMENT_JOURNALPOST }}@bidrag-dokument-journalpost",
                "${{ env.INGRESS_TESTDATA }}@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@sakjournal"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@sakjournal"], "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":["${{ env.INGRESS_DOKUMENT }}@bidrag-dokument"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@avviksbehandling, todo: fix tests and unignore"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@avviksbehandling"], "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":[
                "${{ env.INGRESS_DOKUMENT }}@bidrag-dokument",
                "${{ env.INGRESS_TESTDATA }}@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-dokument-arkiv:
    runs-on: self-hosted
    name: bidrag-dokument-arkiv
    needs: deploy

    env:
      INGRESS_ARKIV: https://bidrag-dokument-arkiv.dev.intern.nav.no
      INGRESS_SAF: https://dokarkiv-q2.dev.adeo.no
      INGRESS_TESTDATA: https://bidrag-testdata.dev.adeo.no

    steps:
      - run: |
          echo "INGRESS_ARKIV=https://bidrag-dokument-arkiv-feature.dev.intern.nav.no" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-onprem-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_SAF=https://dokarkiv-q1.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_TESTDATA=https://bidrag-testdata-feature.dev.adeo.no" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      - name: "@arkiv-swagger"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@arkiv-swagger"],
              "ingressesForApps":["${{ env.INGRESS_ARKIV }}@bidrag-dokument-arkiv"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@bidrag-dokument-arkiv"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@bidrag-dokument-arkiv"], "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":["${{ env.INGRESS_ARKIV }}@bidrag-dokument-arkiv"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@arkiv-saf"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@arkiv-saf"], "navUsername": "c151787", "testUsername": "z992903",
              "noContextPathForApps":["dokarkiv-api"],"ingressesForApps":[
                "${{ env.INGRESS_ARKIV }}@bidrag-dokument-arkiv",
                "${{ env.INGRESS_SAF }}@dokarkiv-api",
                "${{ env.INGRESS_TESTDATA }}@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-person:
    runs-on: self-hosted
    name: bidrag-person
    needs: deploy

    env:
      INGRESS_PERSON: https://bidrag-person.dev.intern.nav.no

    steps:
      - run: |
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-onprem-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_PERSON=https://bidrag-person-feature.dev.intern.nav.no" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      - run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":["${{ env.INGRESS_PERSON }}@tag:bidrag-person"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-organisasjon:
    runs-on: self-hosted
    name: bidrag-organisasjon
    needs: deploy

    env:
      INGRESS_ORGANISASJON: https://bidrag-organisasjon.dev.intern.nav.no

    steps:
      - run: |
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-onprem-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_ORGANISASJON=https://bidrag-organisasjon-feature.dev.intern.nav.no" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      - run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":["${{ env.INGRESS_ORGANISASJON }}@tag:bidrag-organisasjon"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-sak:
    runs-on: self-hosted
    name: bidrag-sak
    needs: deploy

    env:
      INGRESS_SAK: https://bidrag-sak.dev.intern.nav.no

    steps:
      - run: |
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-onprem-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_SAK=https://bidrag-sak-feature.dev.intern.nav.no" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      - run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":["${{ env.INGRESS_SAK }}@tag:bidrag-sak"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-sjablon:
    runs-on: self-hosted
    name: bidrag-sjablon
    needs: deploy

    env:
      INGRESS_SJABLON: https://bidrag-sjablon.dev.intern.nav.no

    steps:
      - run: |
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-onprem-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_SJABLON=https://bidrag-sjablon-feature.dev.nav.no" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      - run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":["${{ env.INGRESS_SJABLON }}@tag:bidrag-sjablon"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  bump_dev_version:
    runs-on: ubuntu-latest
    name: Bump SNAPSHOT version
    if: github.ref == 'refs/heads/main'
    needs:
      - run-tests-for-cucumber-onprem
      - run-tests-for-bidrag-beregn
      - run-tests-for-dokument
      - run-tests-for-dokument-arkiv
      - run-tests-for-person
      - run-tests-for-organisasjon
      - run-tests-for-sak
      - run-tests-for-sjablon

    steps:
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-git/tag-snap@v1-tag-snap
