name: nightly run of cucumber tests
on:
  schedule:
    - cron: '30 2 * * *'

  push:
    branches:
      - feature/cron-fix

env:
  INGRESS_CUCUMBER: https://bidrag-cucumber-onprem.dev.adeo.no

jobs:

  restart-testdata:
    name: restart bidrag-testdata
    runs-on: self-hosted

    steps:
      - run: "curl -X 'POST' 'https://bidrag-testdata.dev.adeo.no/bidrag-testdata/restart' -H 'accept: */*' -d ''"

  run-tests-for-cucumber-onprem:
    runs-on: self-hosted
    name: bidrag-cucumber-onprem

    steps:
      - run: |
          curl -X 'POST' ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "ingressesForApps":["${{ env.INGRESS_CUCUMBER }}@tag:bidrag-cucumber-onprem"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag @bidrag-cucumber-onprem feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-dokument:
    runs-on: self-hosted
    name: bidrag-dokument
    needs: restart-testdata
    if: ${{ always() }}

    steps:
      - name: "@bda-samt-bdj"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@bda-samt-bdj"], "navUsername": "c151787", "testUsername": "z992903",
              "noContextPathForApps":["dokarkiv-api"],"ingressesForApps":[
                "https://bidrag-dokument-arkiv.dev.intern.nav.no@bidrag-dokument-arkiv",
                "https://dokarkiv-q2.dev.adeo.no@dokarkiv-api",
                "https://bidrag-dokument.dev.intern.nav.no@bidrag-dokument",
                "https://bidrag-dokument-journalpost.dev.adeo.no@bidrag-dokument-journalpost",
                "https://bidrag-testdata.dev.adeo.no@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@sakjournal"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@sakjournal"], "navUsername": "c151787", "testUsername": "z992903",
              "noContextPathForApps":["dokarkiv-api"],"ingressesForApps":[
                "https://bidrag-dokument.dev.intern.nav.no@bidrag-dokument"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@avviksbehandling"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@avviksbehandling"], "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":[
                "https://bidrag-dokument.dev.intern.nav.no@bidrag-dokument",
                "https://bidrag-testdata.dev.adeo.no@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@bdok-journalpost"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@bdok-journalpost"], "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":[
                "https://bidrag-dokument.dev.intern.nav.no@bidrag-dokument",
                "https://bidrag-testdata.dev.adeo.no@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@bdok-mottaksregistrert"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@bdok-mottaksregistrert"], "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":[
                "https://bidrag-dokument.dev.intern.nav.no@bidrag-dokument",
                "https://bidrag-testdata.dev.adeo.no@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@bdok-mot-avvik-*"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":[
                "@bdok-mot-avvik-endre-fagomrade", "@bdok-mot-avvik-inn2ut", "@bdok-mot-avvik-best-org", "@bdok-mot-avvik-best-org",
                "@bdok-mot-avvik-best-reskan", "@bdok-mot-avvik-best-splitt"
              ],
              "navUsername": "c151787", "testUsername": "z992903",
              "noContextPathForApps":["dokarkiv-api"], "ingressesForApps":[
                "https://bidrag-dokument.dev.intern.nav.no@bidrag-dokument",
                "https://dokarkiv-q2.dev.adeo.no@dokarkiv-api",
                "https://bidrag-testdata.dev.adeo.no@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot-onprem\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag on bidrag-dokument feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-dokument-arkiv:
    runs-on: self-hosted
    name: bidrag-dokument-arkiv

    env:
      INGRESS_ARKIV: https://bidrag-dokument-arkiv.dev.adeo.no

    steps:
      - name: "@arkiv-swagger"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@arkiv-swagger"],
              "ingressesForApps":["${{ env.INGRESS_ARKIV }}@bidrag-dokument-arkiv"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@bidrag-dokument-arkiv"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@bidrag-dokument-arkiv"], "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":["${{ env.INGRESS_ARKIV }}@bidrag-dokument-arkiv"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@arkiv-saf"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@arkiv-saf"], "navUsername": "c151787", "testUsername": "z992903",
              "noContextPathForApps":["dokarkiv-api"],"ingressesForApps":[
                "${{ env.INGRESS_ARKIV }}@bidrag-dokument-arkiv",
                "${{ env.INGRESS_SAF }}@dokarkiv-api"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot-onprem\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag on bidrag-dokument-arkiv feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-dokument-journalpost:
    runs-on: self-hosted
    name: bidrag-dokument-journalpost
    needs: run-tests-for-dokument  # deleting testdata will cause ObjectOptimisticLockingFailureException if not started after tests of bidrag-dokument
    if: ${{ always() }}

    env:
      INGRESS_DOKARKIV: https://dokarkiv-q2.dev.adeo.no
      INGRESS_DOKUMENT_JOURNALPOST: https://bidrag-dokument-journalpost.dev.adeo.no
      INGRESS_TESTDATA: https://bidrag-testdata.dev.adeo.no

    steps:
      - name: "@bdj-mot-avvik-*"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":[
                "@bdj-mot-avvik-best-org", "@bdj-mot-avvik-best-reskan", "@bdj-mot-avvik-best-splitt",
                "@bdj-mot-avvik-endre-fagomrade", "@bdj-mot-avvik-inn2ut"
              ],
              "navUsername": "c151787", "testUsername": "z992903",
              "noContextPathForApps":["dokarkiv-api"], "ingressesForApps":[
                "https://bidrag-dokument-journalpost.dev.adeo.no@bidrag-dokument-journalpost",
                "https://bidrag-testdata.dev.adeo.no@bidrag-testdata",
                "https://dokarkiv-q2.dev.adeo.no@dokarkiv-api"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@bdj-mottaksregistrert"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@bdj-mottaksregistrert"],
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":[
                "https://bidrag-dokument-journalpost.dev.adeo.no@bidrag-dokument-journalpost",
                "https://bidrag-testdata.dev.adeo.no@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@bdj-sakjournal"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@bdj-sakjournal"],
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":[
                "https://bidrag-dokument-journalpost.dev.adeo.no@bidrag-dokument-journalpost",
                "https://bidrag-testdata.dev.adeo.no@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@bdj-journalpost"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@bdj-journalpost"],
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":[
                "https://bidrag-dokument-journalpost.dev.adeo.no@bidrag-dokument-journalpost",
                "https://bidrag-testdata.dev.adeo.no@bidrag-testdata"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@avvik-*"
        if: ${{ always() }}
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":[
                "@avvik-best-org", "@avvik-best-reskan", "@avvik-best-splitt",
                "@avvik-endre-fagomrade", "@avvik-feilfore-sak", "@avvik-inn2ut", "@avvik-slett-jp"
              ],
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":[
                "https://bidrag-dokument-journalpost.dev.adeo.no@bidrag-dokument-journalpost",
                "https://bidrag-testdata.dev.adeo.no@bidrag-testdata",
                "https://dokarkiv-q2.dev.adeo.no@dokarkiv-api"
              ]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot-onprem\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag on bidrag-dokument-journalpost feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-organisasjon:
    runs-on: self-hosted
    name: bidrag-organisasjon

    steps:
      - run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":["https://bidrag-organisasjon.dev.intern.nav.no@tag:bidrag-organisasjon"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot-onprem\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag @bidrag-organisasjon feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-person:
    runs-on: self-hosted
    name: bidrag-person

    steps:
      - run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":["https://bidrag-person.dev.intern.nav.no@tag:bidrag-person"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot-onprem\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag @bidrag-person feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-sak:
    runs-on: self-hosted
    name: bidrag-sak

    steps:
      - run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "navUsername": "c151787", "testUsername": "z992903",
              "ingressesForApps":["https://bidrag-sak.dev.intern.nav.no@tag:bidrag-sak"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot-onprem\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag @bidrag-sak feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-arkivering:
    runs-on: self-hosted
    name: bidrag-dokument-arkivering
    needs: run-tests-for-dokument-journalpost  # deleting testdata will cause ObjectOptimisticLockingFailureException if not started after tests of bidrag-dokument-journalpost

    steps:
      - run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
          -H 'accept: */*' \
          -H 'Content-Type: application/json' \
          -d '{
           "navUsername": "c151787", "testUsername": "z992903",
           "tags":["@bidrag-dokument-arkivering"],
           "noContextPathForApps": ["bidrag-dokument-arkivering"],
           "ingressesForApps":["https://bidrag-dokument-arkivering.dev.adeo.no@tag:bidrag-dokument-arkivering", "https://bidrag-testdata.dev.adeo.no@bidrag-testdata"]
          }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot-onprem\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag @bidrag-dokument-arkivering feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}