name: nightly run of cucumber tests
on:
  schedule:
    - cron: '30 2 * * *'

  push:
    branches:
      - feature/cron-fix

env:
  INGRESS_CUCUMBER: https://bidrag-cucumber-onprem.dev.adeo.no

jobs:

  run-tests-for-cucumber-onprem:
    runs-on: self-hosted
    name: bidrag-cucumber-onprem

    steps:
      - run: |
          curl -X 'POST' ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "ingressesForApps":["${{ env.INGRESS_CUCUMBER }}@bidrag-cucumber-onprem"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag @bidrag-cucumber-onprem feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-bidrag-beregn:
    runs-on: self-hosted
    name: bidrag-beregn-*

    env:
      INGRESS_BARNEBIDRAG: https://bidrag-beregn-barnebidrag-rest.dev.adeo.no
      INGRESS_FORSKUDD: https://bidrag-beregn-forskudd-rest.dev.adeo.no
      INGRESS_SAERTILSKUDD: https://bidrag-beregn-saertilskudd-rest.dev.adeo.no

    steps:
      - name: bidrag-beregn-barnebidrag-rest
        run: |
          curl -X 'POST' ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "ingressesForApps":["${{ env.INGRESS_BARNEBIDRAG }}@bidrag-beregn-barnebidrag-rest"]
          }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: bidrag-beregn-forskudd-rest
        run: |
          curl -X 'POST' ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "ingressesForApps":["${{ env.INGRESS_FORSKUDD }}@bidrag-beregn-forskudd-rest"]
          }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: bidrag-beregn-saertilskudd-rest
        run: |
          curl -X 'POST' ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "ingressesForApps":["${{ env.INGRESS_SAERTILSKUDD }}@bidrag-beregn-saertilskudd-rest"]
          }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot-onprem\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tags @bidrag-beregn-* feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-dokument-arkiv:
    runs-on: self-hosted
    name: bidrag-dokument-arkiv

    env:
      INGRESS_ARKIV: https://bidrag-dokument-arkiv.dev.adeo.no

    steps:
      - name: "@arkiv-swagger"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@arkiv-swagger"],
              "ingressesForApps":["${{ env.INGRESS_ARKIV }}@no-tag:bidrag-dokument-arkiv"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: "@bidrag-dokument-arkiv"
        run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "tags":["@bidrag-dokument-arkiv"], "navUsername": "j104364", "testUsername": "z992903",
              "ingressesForApps":["${{ env.INGRESS_ARKIV }}@no-tag:bidrag-dokument-arkiv"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot-onprem\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag on bidrag-dokument-arkiv feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-person:
    runs-on: self-hosted
    name: bidrag-person

    env:
      INGRESS_PERSON: https://bidrag-person.dev.intern.nav.no

    steps:
      - run: |
          curl -X 'POST' '${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-onprem/run' -i \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
              "navUsername": "j104364", "testUsername": "z992903",
              "ingressesForApps":["${{ env.INGRESS_PERSON }}@bidrag-person"]
            }' | tee .cucumber-result
          cat .cucumber-result | grep HTTP/1.1 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot-onprem\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-onprem/actions|Cucumber tests> for tag @bidrag-person feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
